### ISSUE TITLE
feat(data): 1 download a tweet mentioning Emmanuel Macron with a script

### ISSUE THREAD

**Issue by qfeuilla** [42-AI/SentimentalBB#13]
# 📖 Describe what you want

Register a file in src/data, that will download a tweet which mention Emmanuel macron and saves it in `data/raw/twitter/user/`

# ✔️ Definition of done

When a tweet will be registered in above folder by running a script in `src/data`

**Comment by ezalos** [comment]
This resource might be useful:

(https://github.com/twitterdev/search-tweets-python)[https://github.com/twitterdev/search-tweets-python]

Usage example:

```python
from searchtweets import ResultStream, gen_rule_payload, load_credentials

rule = gen_rule_payload("from:jack",
                        from_date="2017-09-01", #UTC 2017-09-01 00:00
                        to_date="2017-10-30",#UTC 2017-10-30 00:00
                        results_per_call=500)
print(rule)
{"query":"from:jack","maxResults":500,"toDate":"201710300000","fromDate":"201709010000"}
tweets = collect_results(rule, max_results=500, result_stream_args=enterprise_search_args)
[print(tweet.all_text) for tweet in tweets[0:10]];
```
